kafka:
  topic: "hypertrail-dev-v2"
  brokers: ["54.81.123.72:9093"]
  group: "freshservice-workflow-service"
  sasl_username: "JFMDSFVTTY2BXQT2"
  sasl_password: "5F(Ug5eYRb2YcKZaaYp9V@uK(PMg^3oy7hYW6E4e^6#N@f3ZyCU6DSg4wjHSu$s!"
key_pattern:
  - "workspace_create"
  - "account_create"
  - "workspace_destroy"
  - "account_destroy"