kafka:
  topic: "hypertrail-dev-v2"
  brokers: []
  group: "freshservice-workflow-service"
  sasl_username: ""
  sasl_password: ""
key_pattern:
  - "workspace_create"
  - "account_create"
  - "workspace_destroy"
  - "account_destroy"